sonar.projectKey=kiloecho-sonar_SQ-migration-tool
sonar.organization=kiloecho
sonar.host.url=https://sc-staging.io
sonar.python.version=3.14
sonar.python.coverage.reportPaths=files/coverage.xml
sonar.sources=src
sonar.tests=tests


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=SQ-migration-tool
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
