sonar.projectKey=sonar-solutions_sonar-reports
sonar.organization=sonar-solutions

sonar.go.coverage.reportPaths=lib/sq-api-go/coverage.sonar.out,go/coverage.sonar.out
sonar.sources=lib/sq-api-go,go/cmd,go/internal,go/main.go
sonar.tests=go/internal
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*.pb.go,go/internal/gui/frontend/**
sonar.coverage.exclusions=**/*_test.go,**/cli_prompter.go,**/*.pb.go,go/cmd/**
sonar.cpd.exclusions=**/*_test.go
