// SonarQube, open source software quality management tool.
// Copyright (C) 2008-2016 SonarSource
// mailto:contact AT sonarsource DOT com
//
// SonarQube is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 3 of the License, or (at your option) any later version.
//
// SonarQube is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program; if not, write to the Free Software Foundation,
// Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: constants.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Severity int32

const (
	Severity_UNSET_SEVERITY Severity = 0
	Severity_INFO           Severity = 1
	Severity_MINOR          Severity = 2
	Severity_MAJOR          Severity = 3
	Severity_CRITICAL       Severity = 4
	Severity_BLOCKER        Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "UNSET_SEVERITY",
		1: "INFO",
		2: "MINOR",
		3: "MAJOR",
		4: "CRITICAL",
		5: "BLOCKER",
	}
	Severity_value = map[string]int32{
		"UNSET_SEVERITY": 0,
		"INFO":           1,
		"MINOR":          2,
		"MAJOR":          3,
		"CRITICAL":       4,
		"BLOCKER":        5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_constants_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_constants_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_constants_proto_rawDescGZIP(), []int{0}
}

var File_constants_proto protoreflect.FileDescriptor

const file_constants_proto_rawDesc = "" +
	"\n" +
	"\x0fconstants.proto\x12\n" +
	"scanreport*Y\n" +
	"\bSeverity\x12\x12\n" +
	"\x0eUNSET_SEVERITY\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\t\n" +
	"\x05MINOR\x10\x02\x12\t\n" +
	"\x05MAJOR\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04\x12\v\n" +
	"\aBLOCKER\x10\x05BMH\x01ZIgithub.com/sonar-solutions/sonar-migration-tool/internal/scanreport/protob\x06proto3"

var (
	file_constants_proto_rawDescOnce sync.Once
	file_constants_proto_rawDescData []byte
)

func file_constants_proto_rawDescGZIP() []byte {
	file_constants_proto_rawDescOnce.Do(func() {
		file_constants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constants_proto_rawDesc), len(file_constants_proto_rawDesc)))
	})
	return file_constants_proto_rawDescData
}

var file_constants_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_constants_proto_goTypes = []any{
	(Severity)(0), // 0: scanreport.Severity
}
var file_constants_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_constants_proto_init() }
func file_constants_proto_init() {
	if File_constants_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constants_proto_rawDesc), len(file_constants_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constants_proto_goTypes,
		DependencyIndexes: file_constants_proto_depIdxs,
		EnumInfos:         file_constants_proto_enumTypes,
	}.Build()
	File_constants_proto = out.File
	file_constants_proto_goTypes = nil
	file_constants_proto_depIdxs = nil
}
